# Generated by Django 5.2.4 on 2025-07-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_remove_expense_paid_by_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Debt",
        ),
    ]
